# Generated by Django 5.1.2 on 2024-10-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='puntos_subasta',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
