# Generated by Django 5.1.2 on 2024-10-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_empleado_puntos_subasta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
