# Generated by Django 5.1.2 on 2024-10-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_delete_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='dv',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='run',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
