# Generated by Django 5.1.2 on 2024-11-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_empleado_direccion_empleado_dv_empleado_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='puntos',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puntos_subasta',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
