# Generated by Django 5.1.1 on 2024-10-03 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='PaisOrigen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_iso', models.CharField(max_length=255, verbose_name='Código ISO')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('abv', models.FloatField(verbose_name='Alc. (%)')),
                ('contenido', models.FloatField(verbose_name='Cont. Neto (ml)')),
                ('envase', models.CharField(max_length=255, verbose_name='Envase')),
                ('puntos_requeridos', models.PositiveIntegerField(verbose_name='Puntos Requeridos')),
                ('precio', models.FloatField(verbose_name='Precio (CLP)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('unidades', models.PositiveIntegerField(default=0, verbose_name='Unidades')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria', verbose_name='Categoría')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.marca', verbose_name='Marca')),
                ('pais_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.paisorigen', verbose_name='País de Origen')),
            ],
        ),
    ]
