# Generated by Django 5.1.2 on 2024-10-14 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=255, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=255, verbose_name='Teléfono')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.proveedor', verbose_name='Proveedor'),
            preserve_default=False,
        ),
    ]
