# Generated by Django 5.1.2 on 2024-10-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_proveedor_producto_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nombre',
        ),
    ]
