# Generated by Django 5.1.2 on 2024-10-17 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_name_categoria_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='envase',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='puntos_iniciales',
            field=models.PositiveIntegerField(default=0, verbose_name='Puntos Iniciales'),
        ),
    ]
