# Generated by Django 5.1.2 on 2024-10-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_envase_remove_producto_precio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaisOrigen',
            new_name='Procedencia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidades',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default=1, max_length=255, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
