# Generated by Django 5.1.2 on 2024-10-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_marca_imagen_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/marcas', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/productos', verbose_name='Imagen'),
        ),
    ]
