# Generated by Django 5.1.2 on 2024-11-03 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_marca_imagen_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
    ]
