# Generated by Django 5.1.2 on 2024-11-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
    ]
