# Generated by Django 5.1.2 on 2024-11-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_producto_destacado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='puntos_iniciales',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(default=1, verbose_name='Precio'),
            preserve_default=False,
        ),
    ]
