# Generated by Django 5.1.2 on 2024-11-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_remove_producto_puntos_iniciales_producto_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_unitario',
        ),
    ]
