# Generated by Django 5.1.2 on 2024-10-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='categoria',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
