# Generated by Django 5.1.2 on 2024-10-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccionpuntos',
            old_name='created_at',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='transaccionpuntos',
            old_name='perfil',
            new_name='usuario',
        ),
    ]
