# Generated by Django 5.1.2 on 2024-11-12 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_usuario'),
        ('productos', '0013_rename_precio_producto_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
            preserve_default=False,
        ),
    ]
