# Generated by Django 5.1.2 on 2024-10-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='cerrado',
            field=models.BooleanField(default=False),
        ),
    ]
