# Generated by Django 5.1.2 on 2024-10-19 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_delete_rol'),
        ('sorteo', '0004_participacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacion',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roles.empleado'),
        ),
    ]
