# Generated by Django 5.1.2 on 2024-10-20 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_delete_rol'),
        ('sorteo', '0005_alter_participacion_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteo',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roles.empleado'),
            preserve_default=False,
        ),
    ]
