# Generated by Django 5.1.2 on 2024-10-20 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0006_alter_sorteo_empleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorteo',
            name='empleado',
        ),
    ]
