# Generated by Django 5.1.2 on 2024-10-20 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_delete_rol'),
        ('sorteo', '0007_remove_sorteo_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participacion',
            name='empleado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roles.empleado'),
            preserve_default=False,
        ),
    ]
