# Generated by Django 5.1.2 on 2024-10-22 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_delete_rol'),
        ('subasta', '0002_alter_puja_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puja',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to='roles.empleado'),
        ),
    ]
