# Generated by Django 5.1.2 on 2024-11-11 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subasta', '0003_alter_puja_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='numero_rondas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subasta',
            name='ronda_actual',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subasta',
            name='tiempo_entre_rondas',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
        ),
        migrations.AddField(
            model_name='subasta',
            name='ultima_ronda',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
