# Generated by Django 5.1.2 on 2024-11-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subasta', '0004_subasta_numero_rondas_subasta_ronda_actual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='numero_rondas',
        ),
        migrations.RemoveField(
            model_name='subasta',
            name='ronda_actual',
        ),
        migrations.RemoveField(
            model_name='subasta',
            name='tiempo_entre_rondas',
        ),
        migrations.RemoveField(
            model_name='subasta',
            name='ultima_ronda',
        ),
    ]
