# Generated by Django 5.1.2 on 2024-10-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_pedido', '0002_alter_ordenpedido_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpedido',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
