# Generated by Django 5.1.2 on 2024-10-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_pedido', '0003_ordenpedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenpedido',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
