# Generated by Django 5.1.2 on 2024-11-10 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_pedido', '0004_alter_ordenpedido_estado'),
        ('roles', '0006_alter_empleado_puntos_alter_empleado_puntos_subasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenpedido',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_pedido', to='roles.empleado'),
        ),
    ]
