# Generated by Django 5.1.2 on 2024-11-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_pedido', '0006_alter_ordenpedido_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpedido',
            name='total_precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
