# Generated by Django 5.1.2 on 2024-11-10 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_pedido', '0007_ordenpedido_total_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenpedido',
            old_name='total_precio',
            new_name='monto_neto',
        ),
    ]
