# Generated by Django 5.1.2 on 2024-11-11 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_pedido', '0008_rename_total_precio_ordenpedido_monto_neto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenpedido',
            name='monto_neto',
        ),
    ]
