# Generated by Django 5.1.2 on 2024-11-11 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_pedido', '0009_remove_ordenpedido_monto_neto'),
        ('roles', '0006_alter_empleado_puntos_alter_empleado_puntos_subasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenpedido',
            name='razon_social',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='razon_social', to='roles.empleado'),
            preserve_default=False,
        ),
    ]
