# Generated by Django 5.1.2 on 2024-10-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canjeo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canjeo',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
